const TrackLayouts = {
  defaultKeyPoints: [
    {
      x: 650,
      y: 500,
      type: "straight",
      zone: "Main Straight",
      sector: 3,
      targetSpeed: 310,
    },
    {
      x: 350,
      y: 500,
      type: "straight",
      zone: "Main Straight",
      sector: 3,
      targetSpeed: 330,
    },
    {
      x: 140,
      y: 500,
      type: "corner",
      zone: "Turn 1 (Hairpin)",
      sector: 1,
      targetSpeed: 82,
    },
    {
      x: 175,
      y: 440,
      type: "corner",
      zone: "Turn 2-3",
      sector: 1,
      targetSpeed: 135,
    },
    {
      x: 155,
      y: 390,
      type: "straight",
      zone: "Sector 1 Straight",
      sector: 1,
      targetSpeed: 295,
    },
    {
      x: 185,
      y: 70,
      type: "corner",
      zone: "Turn 4",
      sector: 1,
      targetSpeed: 110,
    },
    {
      x: 320,
      y: 150,
      type: "corner",
      zone: "Turn 5-6",
      sector: 2,
      targetSpeed: 175,
    },
    {
      x: 370,
      y: 175,
      type: "corner",
      zone: "Turn 7",
      sector: 2,
      targetSpeed: 155,
    },
    {
      x: 345,
      y: 220,
      type: "straight",
      zone: "Downhill Straight",
      sector: 2,
      targetSpeed: 245,
    },
    {
      x: 480,
      y: 340,
      type: "corner",
      zone: "Turn 8 (Hairpin)",
      sector: 2,
      targetSpeed: 88,
    },
    {
      x: 270,
      y: 315,
      type: "corner",
      zone: "Turn 9",
      sector: 2,
      targetSpeed: 125,
    },
    {
      x: 215,
      y: 375,
      type: "straight",
      zone: "Sector 2 Straight",
      sector: 2,
      targetSpeed: 295,
    },
    {
      x: 630,
      y: 395,
      type: "corner",
      zone: "Turn 11",
      sector: 2,
      targetSpeed: 165,
    },
    {
      x: 540,
      y: 220,
      type: "corner",
      zone: "Turn 12",
      sector: 3,
      targetSpeed: 205,
    },
    {
      x: 600,
      y: 70,
      type: "corner",
      zone: "Turn 13",
      sector: 3,
      targetSpeed: 135,
    },
    {
      x: 830,
      y: 460,
      type: "corner",
      zone: "Turn 14",
      sector: 3,
      targetSpeed: 115,
    },
    {
      x: 800,
      y: 500,
      type: "straight",
      zone: "Main Straight",
      sector: 3,
      targetSpeed: 265,
    },
  ],

  layouts: {
    bahrain: [
      {
        x: 650,
        y: 500,
        type: "straight",
        zone: "Main Straight",
        sector: 3,
        targetSpeed: 310,
      },
      {
        x: 350,
        y: 500,
        type: "straight",
        zone: "Main Straight",
        sector: 3,
        targetSpeed: 330,
      },
      {
        x: 140,
        y: 500,
        type: "corner",
        zone: "Turn 1 (Hairpin)",
        sector: 1,
        targetSpeed: 82,
      },
      {
        x: 175,
        y: 440,
        type: "corner",
        zone: "Turn 2-3",
        sector: 1,
        targetSpeed: 135,
      },
      {
        x: 155,
        y: 390,
        type: "straight",
        zone: "Sector 1 Straight",
        sector: 1,
        targetSpeed: 295,
      },
      {
        x: 185,
        y: 70,
        type: "corner",
        zone: "Turn 4",
        sector: 1,
        targetSpeed: 110,
      },
      {
        x: 320,
        y: 150,
        type: "corner",
        zone: "Turn 5-6",
        sector: 2,
        targetSpeed: 175,
      },
      {
        x: 370,
        y: 175,
        type: "corner",
        zone: "Turn 7",
        sector: 2,
        targetSpeed: 155,
      },
      {
        x: 345,
        y: 220,
        type: "straight",
        zone: "Downhill Straight",
        sector: 2,
        targetSpeed: 245,
      },
      {
        x: 480,
        y: 340,
        type: "corner",
        zone: "Turn 8 (Hairpin)",
        sector: 2,
        targetSpeed: 88,
      },
      {
        x: 270,
        y: 315,
        type: "corner",
        zone: "Turn 9",
        sector: 2,
        targetSpeed: 125,
      },
      {
        x: 215,
        y: 375,
        type: "straight",
        zone: "Sector 2 Straight",
        sector: 2,
        targetSpeed: 295,
      },
      {
        x: 630,
        y: 395,
        type: "corner",
        zone: "Turn 11",
        sector: 2,
        targetSpeed: 165,
      },
      {
        x: 540,
        y: 220,
        type: "corner",
        zone: "Turn 12",
        sector: 3,
        targetSpeed: 205,
      },
      {
        x: 600,
        y: 70,
        type: "corner",
        zone: "Turn 13",
        sector: 3,
        targetSpeed: 135,
      },
      {
        x: 830,
        y: 460,
        type: "corner",
        zone: "Turn 14",
        sector: 3,
        targetSpeed: 115,
      },
      {
        x: 800,
        y: 500,
        type: "straight",
        zone: "Main Straight",
        sector: 3,
        targetSpeed: 265,
      },
    ],
    albert_park: [
      {
        x: 650,
        y: 500,
        type: "straight",
        zone: "Main Straight",
        sector: 3,
        targetSpeed: 300,
      },
      {
        x: 300,
        y: 500,
        type: "straight",
        zone: "Main Straight",
        sector: 3,
        targetSpeed: 315,
      },
      {
        x: 150,
        y: 480,
        type: "corner",
        zone: "Turn 1",
        sector: 1,
        targetSpeed: 120,
      },
      {
        x: 100,
        y: 400,
        type: "corner",
        zone: "Turn 2",
        sector: 1,
        targetSpeed: 150,
      },
      {
        x: 120,
        y: 300,
        type: "straight",
        zone: "Straight",
        sector: 1,
        targetSpeed: 280,
      },
      {
        x: 250,
        y: 100,
        type: "corner",
        zone: "Turn 3-4",
        sector: 1,
        targetSpeed: 220,
      },
      {
        x: 400,
        y: 100,
        type: "straight",
        zone: "Straight",
        sector: 2,
        targetSpeed: 290,
      },
      {
        x: 550,
        y: 150,
        type: "corner",
        zone: "Turn 6",
        sector: 2,
        targetSpeed: 180,
      },
      {
        x: 600,
        y: 250,
        type: "straight",
        zone: "Straight",
        sector: 2,
        targetSpeed: 270,
      },
      {
        x: 700,
        y: 350,
        type: "corner",
        zone: "Turn 9-10",
        sector: 3,
        targetSpeed: 100,
      },
      {
        x: 650,
        y: 450,
        type: "straight",
        zone: "Straight",
        sector: 3,
        targetSpeed: 295,
      },
      {
        x: 500,
        y: 480,
        type: "corner",
        zone: "Turn 11",
        sector: 3,
        targetSpeed: 160,
      },
      {
        x: 400,
        y: 450,
        type: "corner",
        zone: "Turn 12",
        sector: 3,
        targetSpeed: 180,
      },
    ],
    shanghai: [
      {
        x: 650,
        y: 500,
        type: "straight",
        zone: "Main Straight",
        sector: 3,
        targetSpeed: 320,
      },
      {
        x: 350,
        y: 500,
        type: "straight",
        zone: "Main Straight",
        sector: 3,
        targetSpeed: 335,
      },
      {
        x: 150,
        y: 480,
        type: "corner",
        zone: "Turn 1-2",
        sector: 1,
        targetSpeed: 80,
      },
      {
        x: 100,
        y: 200,
        type: "corner",
        zone: "Turn 3",
        sector: 1,
        targetSpeed: 140,
      },
      {
        x: 200,
        y: 100,
        type: "straight",
        zone: "Straight",
        sector: 1,
        targetSpeed: 290,
      },
      {
        x: 400,
        y: 100,
        type: "corner",
        zone: "Turn 6",
        sector: 2,
        targetSpeed: 160,
      },
      {
        x: 500,
        y: 200,
        type: "straight",
        zone: "Straight",
        sector: 2,
        targetSpeed: 270,
      },
      {
        x: 550,
        y: 350,
        type: "corner",
        zone: "Turn 7-8",
        sector: 2,
        targetSpeed: 100,
      },
      {
        x: 400,
        y: 400,
        type: "straight",
        zone: "Straight",
        sector: 2,
        targetSpeed: 310,
      },
      {
        x: 200,
        y: 450,
        type: "corner",
        zone: "Turn 11",
        sector: 3,
        targetSpeed: 130,
      },
      {
        x: 180,
        y: 500,
        type: "straight",
        zone: "Straight",
        sector: 3,
        targetSpeed: 300,
      },
    ],
    suzuka: [
      {
        x: 650,
        y: 500,
        type: "straight",
        zone: "Main Straight",
        sector: 3,
        targetSpeed: 300,
      },
      {
        x: 350,
        y: 500,
        type: "straight",
        zone: "Main Straight",
        sector: 3,
        targetSpeed: 320,
      },
      {
        x: 150,
        y: 480,
        type: "corner",
        zone: "Turn 1-2",
        sector: 1,
        targetSpeed: 200,
      },
      {
        x: 200,
        y: 200,
        type: "corner",
        zone: "Turn 3-6",
        sector: 1,
        targetSpeed: 180,
      },
      {
        x: 400,
        y: 100,
        type: "straight",
        zone: "Straight",
        sector: 2,
        targetSpeed: 280,
      },
      {
        x: 550,
        y: 150,
        type: "corner",
        zone: "Turn 7-8",
        sector: 2,
        targetSpeed: 160,
      },
      {
        x: 600,
        y: 350,
        type: "straight",
        zone: "Straight",
        sector: 2,
        targetSpeed: 290,
      },
      {
        x: 400,
        y: 450,
        type: "corner",
        zone: "Spoon Curve",
        sector: 3,
        targetSpeed: 140,
      },
      {
        x: 200,
        y: 400,
        type: "straight",
        zone: "130R",
        sector: 3,
        targetSpeed: 300,
      },
      {
        x: 180,
        y: 500,
        type: "corner",
        zone: "Chicane",
        sector: 3,
        targetSpeed: 80,
      },
    ],
    jeddah: [
      {
        x: 650,
        y: 500,
        type: "straight",
        zone: "Main Straight",
        sector: 3,
        targetSpeed: 310,
      },
      {
        x: 350,
        y: 500,
        type: "straight",
        zone: "Main Straight",
        sector: 3,
        targetSpeed: 325,
      },
      {
        x: 150,
        y: 480,
        type: "corner",
        zone: "Esses",
        sector: 1,
        targetSpeed: 250,
      },
      {
        x: 100,
        y: 200,
        type: "corner",
        zone: "Turns 4-10",
        sector: 1,
        targetSpeed: 200,
      },
      {
        x: 200,
        y: 100,
        type: "straight",
        zone: "Straight",
        sector: 1,
        targetSpeed: 300,
      },
      {
        x: 400,
        y: 100,
        type: "corner",
        zone: "Turns 13-15",
        sector: 2,
        targetSpeed: 180,
      },
      {
        x: 500,
        y: 200,
        type: "straight",
        zone: "Straight",
        sector: 2,
        targetSpeed: 310,
      },
      {
        x: 550,
        y: 350,
        type: "corner",
        zone: "Turns 20-22",
        sector: 2,
        targetSpeed: 120,
      },
      {
        x: 400,
        y: 400,
        type: "straight",
        zone: "Straight",
        sector: 3,
        targetSpeed: 320,
      },
      {
        x: 200,
        y: 450,
        type: "corner",
        zone: "Turn 27",
        sector: 3,
        targetSpeed: 90,
      },
      {
        x: 180,
        y: 500,
        type: "straight",
        zone: "Start-Finish",
        sector: 3,
        targetSpeed: 300,
      },
    ],
    miami: [
      {
        x: 650,
        y: 500,
        type: "straight",
        zone: "Main Straight",
        sector: 3,
        targetSpeed: 305,
      },
      {
        x: 350,
        y: 500,
        type: "straight",
        zone: "Main Straight",
        sector: 3,
        targetSpeed: 320,
      },
      {
        x: 150,
        y: 480,
        type: "corner",
        zone: "Turn 1",
        sector: 1,
        targetSpeed: 100,
      },
      {
        x: 100,
        y: 300,
        type: "straight",
        zone: "Straight",
        sector: 1,
        targetSpeed: 270,
      },
      {
        x: 200,
        y: 100,
        type: "corner",
        zone: "Turns 4-5",
        sector: 1,
        targetSpeed: 150,
      },
      {
        x: 400,
        y: 100,
        type: "straight",
        zone: "Straight",
        sector: 2,
        targetSpeed: 290,
      },
      {
        x: 550,
        y: 150,
        type: "corner",
        zone: "Turn 11",
        sector: 2,
        targetSpeed: 120,
      },
      {
        x: 600,
        y: 350,
        type: "straight",
        zone: "Straight",
        sector: 2,
        targetSpeed: 310,
      },
      {
        x: 400,
        y: 450,
        type: "corner",
        zone: "Turns 14-15",
        sector: 3,
        targetSpeed: 80,
      },
      {
        x: 200,
        y: 400,
        type: "straight",
        zone: "Straight",
        sector: 3,
        targetSpeed: 280,
      },
      {
        x: 180,
        y: 500,
        type: "corner",
        zone: "Turn 16",
        sector: 3,
        targetSpeed: 100,
      },
    ],
    monaco: [
      {
        x: 650,
        y: 500,
        type: "straight",
        zone: "Start-Finish",
        sector: 3,
        targetSpeed: 280,
      },
      {
        x: 350,
        y: 500,
        type: "straight",
        zone: "Start-Finish",
        sector: 3,
        targetSpeed: 295,
      },
      {
        x: 150,
        y: 480,
        type: "corner",
        zone: "Sainte Devote",
        sector: 1,
        targetSpeed: 100,
      },
      {
        x: 100,
        y: 400,
        type: "corner",
        zone: "Massenet",
        sector: 1,
        targetSpeed: 120,
      },
      {
        x: 120,
        y: 300,
        type: "corner",
        zone: "Casino Square",
        sector: 1,
        targetSpeed: 110,
      },
      {
        x: 250,
        y: 100,
        type: "corner",
        zone: "Mirabeau",
        sector: 1,
        targetSpeed: 80,
      },
      {
        x: 400,
        y: 100,
        type: "corner",
        zone: "Loews Hairpin",
        sector: 2,
        targetSpeed: 50,
      },
      {
        x: 550,
        y: 150,
        type: "corner",
        zone: "Portier",
        sector: 2,
        targetSpeed: 100,
      },
      {
        x: 600,
        y: 250,
        type: "straight",
        zone: "Tunnel",
        sector: 2,
        targetSpeed: 300,
      },
      {
        x: 700,
        y: 350,
        type: "corner",
        zone: "Nouvelle Chicane",
        sector: 3,
        targetSpeed: 80,
      },
      {
        x: 650,
        y: 450,
        type: "corner",
        zone: "Tabac",
        sector: 3,
        targetSpeed: 140,
      },
      {
        x: 500,
        y: 480,
        type: "corner",
        zone: "Swimming Pool",
        sector: 3,
        targetSpeed: 180,
      },
    ],
    silverstone: [
      {
        x: 650,
        y: 500,
        type: "straight",
        zone: "Main Straight",
        sector: 3,
        targetSpeed: 300,
      },
      {
        x: 350,
        y: 500,
        type: "straight",
        zone: "Main Straight",
        sector: 3,
        targetSpeed: 320,
      },
      {
        x: 150,
        y: 480,
        type: "corner",
        zone: "Abbey",
        sector: 1,
        targetSpeed: 260,
      },
      {
        x: 100,
        y: 300,
        type: "corner",
        zone: "Copse",
        sector: 1,
        targetSpeed: 280,
      },
      {
        x: 200,
        y: 100,
        type: "straight",
        zone: "Hangar Straight",
        sector: 1,
        targetSpeed: 315,
      },
      {
        x: 400,
        y: 100,
        type: "corner",
        zone: "Stowe",
        sector: 2,
        targetSpeed: 220,
      },
      {
        x: 500,
        y: 200,
        type: "straight",
        zone: "Straight",
        sector: 2,
        targetSpeed: 300,
      },
      {
        x: 550,
        y: 350,
        type: "corner",
        zone: "Maggotts-Becketts",
        sector: 2,
        targetSpeed: 270,
      },
      {
        x: 400,
        y: 400,
        type: "straight",
        zone: "Wellington Straight",
        sector: 3,
        targetSpeed: 310,
      },
      {
        x: 200,
        y: 450,
        type: "corner",
        zone: "Vale-Club",
        sector: 3,
        targetSpeed: 100,
      },
    ],
    spa: [
      {
        x: 650,
        y: 500,
        type: "straight",
        zone: "Start-Finish Straight",
        sector: 3,
        targetSpeed: 310,
      },
      {
        x: 350,
        y: 500,
        type: "straight",
        zone: "Raidillon",
        sector: 1,
        targetSpeed: 320,
      },
      {
        x: 150,
        y: 400,
        type: "corner",
        zone: "Eau Rouge",
        sector: 1,
        targetSpeed: 280,
      },
      {
        x: 100,
        y: 100,
        type: "straight",
        zone: "Kemmel Straight",
        sector: 1,
        targetSpeed: 330,
      },
      {
        x: 300,
        y: 50,
        type: "corner",
        zone: "Les Combes",
        sector: 1,
        targetSpeed: 180,
      },
      {
        x: 500,
        y: 100,
        type: "straight",
        zone: "Straight",
        sector: 2,
        targetSpeed: 290,
      },
      {
        x: 600,
        y: 250,
        type: "corner",
        zone: "Pouhon",
        sector: 2,
        targetSpeed: 250,
      },
      {
        x: 700,
        y: 350,
        type: "straight",
        zone: "Straight",
        sector: 2,
        targetSpeed: 270,
      },
      {
        x: 650,
        y: 450,
        type: "corner",
        zone: "Blanchimont",
        sector: 3,
        targetSpeed: 300,
      },
      {
        x: 500,
        y: 480,
        type: "corner",
        zone: "Bus Stop Chicane",
        sector: 3,
        targetSpeed: 80,
      },
    ],
    hungaroring: [
      {
        x: 650,
        y: 500,
        type: "straight",
        zone: "Main Straight",
        sector: 3,
        targetSpeed: 290,
      },
      {
        x: 350,
        y: 500,
        type: "straight",
        zone: "Main Straight",
        sector: 3,
        targetSpeed: 300,
      },
      {
        x: 150,
        y: 480,
        type: "corner",
        zone: "Turn 1",
        sector: 1,
        targetSpeed: 100,
      },
      {
        x: 100,
        y: 300,
        type: "corner",
        zone: "Turns 2-3",
        sector: 1,
        targetSpeed: 140,
      },
      {
        x: 200,
        y: 100,
        type: "straight",
        zone: "Straight",
        sector: 1,
        targetSpeed: 250,
      },
      {
        x: 400,
        y: 100,
        type: "corner",
        zone: "Turns 4-7",
        sector: 2,
        targetSpeed: 120,
      },
      {
        x: 500,
        y: 200,
        type: "straight",
        zone: "Straight",
        sector: 2,
        targetSpeed: 260,
      },
      {
        x: 550,
        y: 350,
        type: "corner",
        zone: "Turns 8-11",
        sector: 2,
        targetSpeed: 100,
      },
      {
        x: 400,
        y: 400,
        type: "straight",
        zone: "Straight",
        sector: 3,
        targetSpeed: 270,
      },
      {
        x: 200,
        y: 450,
        type: "corner",
        zone: "Turns 12-14",
        sector: 3,
        targetSpeed: 90,
      },
    ],
    zandvoort: [
      {
        x: 650,
        y: 500,
        type: "straight",
        zone: "Main Straight",
        sector: 3,
        targetSpeed: 280,
      },
      {
        x: 350,
        y: 500,
        type: "straight",
        zone: "Main Straight",
        sector: 3,
        targetSpeed: 295,
      },
      {
        x: 150,
        y: 480,
        type: "corner",
        zone: "Tarzanbocht",
        sector: 1,
        targetSpeed: 100,
      },
      {
        x: 100,
        y: 300,
        type: "corner",
        zone: "Turns 2-4",
        sector: 1,
        targetSpeed: 150,
      },
      {
        x: 200,
        y: 100,
        type: "straight",
        zone: "Straight",
        sector: 1,
        targetSpeed: 260,
      },
      {
        x: 400,
        y: 100,
        type: "corner",
        zone: "Hugenholtzbocht",
        sector: 2,
        targetSpeed: 130,
      },
      {
        x: 500,
        y: 200,
        type: "straight",
        zone: "Straight",
        sector: 2,
        targetSpeed: 270,
      },
      {
        x: 550,
        y: 350,
        type: "corner",
        zone: "Scheivlak",
        sector: 2,
        targetSpeed: 200,
      },
      {
        x: 400,
        y: 400,
        type: "straight",
        zone: "Straight",
        sector: 3,
        targetSpeed: 285,
      },
      {
        x: 200,
        y: 450,
        type: "corner",
        zone: "Arie Luyendyk",
        sector: 3,
        targetSpeed: 250,
      },
    ],
    monza: [
      {
        x: 650,
        y: 500,
        type: "straight",
        zone: "Main Straight",
        sector: 3,
        targetSpeed: 340,
      },
      {
        x: 350,
        y: 500,
        type: "straight",
        zone: "Main Straight",
        sector: 3,
        targetSpeed: 350,
      },
      {
        x: 150,
        y: 480,
        type: "corner",
        zone: "Variante del Rettifilo",
        sector: 1,
        targetSpeed: 80,
      },
      {
        x: 100,
        y: 300,
        type: "straight",
        zone: "Curva Grande",
        sector: 1,
        targetSpeed: 280,
      },
      {
        x: 200,
        y: 100,
        type: "corner",
        zone: "Variante della Roggia",
        sector: 1,
        targetSpeed: 120,
      },
      {
        x: 400,
        y: 100,
        type: "straight",
        zone: "Straight",
        sector: 2,
        targetSpeed: 330,
      },
      {
        x: 500,
        y: 200,
        type: "corner",
        zone: "Lesmo 1",
        sector: 2,
        targetSpeed: 180,
      },
      {
        x: 550,
        y: 350,
        type: "corner",
        zone: "Lesmo 2",
        sector: 2,
        targetSpeed: 160,
      },
      {
        x: 400,
        y: 400,
        type: "straight",
        zone: "Straight",
        sector: 3,
        targetSpeed: 320,
      },
      {
        x: 200,
        y: 450,
        type: "corner",
        zone: "Variante Ascari",
        sector: 3,
        targetSpeed: 150,
      },
    ],
    marina_bay: [
      {
        x: 650,
        y: 500,
        type: "straight",
        zone: "Main Straight",
        sector: 3,
        targetSpeed: 280,
      },
      {
        x: 350,
        y: 500,
        type: "straight",
        zone: "Main Straight",
        sector: 3,
        targetSpeed: 290,
      },
      {
        x: 150,
        y: 480,
        type: "corner",
        zone: "Turn 1",
        sector: 1,
        targetSpeed: 100,
      },
      {
        x: 100,
        y: 300,
        type: "corner",
        zone: "Turns 2-3",
        sector: 1,
        targetSpeed: 120,
      },
      {
        x: 200,
        y: 100,
        type: "straight",
        zone: "Straight",
        sector: 1,
        targetSpeed: 250,
      },
      {
        x: 400,
        y: 100,
        type: "corner",
        zone: "Turns 5-7",
        sector: 2,
        targetSpeed: 90,
      },
      {
        x: 500,
        y: 200,
        type: "straight",
        zone: "Straight",
        sector: 2,
        targetSpeed: 260,
      },
      {
        x: 550,
        y: 350,
        type: "corner",
        zone: "Turns 10-13",
        sector: 2,
        targetSpeed: 80,
      },
      {
        x: 400,
        y: 400,
        type: "straight",
        zone: "Straight",
        sector: 3,
        targetSpeed: 270,
      },
      {
        x: 200,
        y: 450,
        type: "corner",
        zone: "Turns 15-18",
        sector: 3,
        targetSpeed: 110,
      },
    ],
    red_bull_ring: [
      {
        x: 650,
        y: 500,
        type: "straight",
        zone: "Main Straight",
        sector: 3,
        targetSpeed: 300,
      },
      {
        x: 350,
        y: 500,
        type: "straight",
        zone: "Main Straight",
        sector: 3,
        targetSpeed: 310,
      },
      {
        x: 150,
        y: 480,
        type: "corner",
        zone: "Turn 1",
        sector: 1,
        targetSpeed: 100,
      },
      {
        x: 100,
        y: 300,
        type: "straight",
        zone: "Straight",
        sector: 1,
        targetSpeed: 280,
      },
      {
        x: 200,
        y: 100,
        type: "corner",
        zone: "Turn 3",
        sector: 1,
        targetSpeed: 120,
      },
      {
        x: 400,
        y: 100,
        type: "straight",
        zone: "Straight",
        sector: 2,
        targetSpeed: 290,
      },
      {
        x: 500,
        y: 200,
        type: "corner",
        zone: "Turn 4",
        sector: 2,
        targetSpeed: 150,
      },
      {
        x: 550,
        y: 350,
        type: "straight",
        zone: "Straight",
        sector: 2,
        targetSpeed: 300,
      },
      {
        x: 400,
        y: 400,
        type: "corner",
        zone: "Turn 6",
        sector: 3,
        targetSpeed: 180,
      },
      {
        x: 200,
        y: 450,
        type: "straight",
        zone: "Straight",
        sector: 3,
        targetSpeed: 270,
      },
    ],
    las_vegas: [
      {
        x: 650,
        y: 500,
        type: "straight",
        zone: "Main Straight",
        sector: 3,
        targetSpeed: 330,
      },
      {
        x: 350,
        y: 500,
        type: "straight",
        zone: "Main Straight",
        sector: 3,
        targetSpeed: 340,
      },
      {
        x: 150,
        y: 480,
        type: "corner",
        zone: "Turn 1",
        sector: 1,
        targetSpeed: 90,
      },
      {
        x: 100,
        y: 300,
        type: "straight",
        zone: "Straight",
        sector: 1,
        targetSpeed: 300,
      },
      {
        x: 200,
        y: 100,
        type: "corner",
        zone: "Turns 5-6",
        sector: 1,
        targetSpeed: 110,
      },
      {
        x: 400,
        y: 100,
        type: "straight",
        zone: "Strip",
        sector: 2,
        targetSpeed: 350,
      },
      {
        x: 500,
        y: 200,
        type: "corner",
        zone: "Turns 11-12",
        sector: 2,
        targetSpeed: 100,
      },
      {
        x: 550,
        y: 350,
        type: "straight",
        zone: "Straight",
        sector: 2,
        targetSpeed: 320,
      },
      {
        x: 400,
        y: 400,
        type: "corner",
        zone: "Turns 14-15",
        sector: 3,
        targetSpeed: 120,
      },
      {
        x: 200,
        y: 450,
        type: "straight",
        zone: "Straight",
        sector: 3,
        targetSpeed: 310,
      },
    ],
    lusail: [
      {
        x: 650,
        y: 500,
        type: "straight",
        zone: "Main Straight",
        sector: 3,
        targetSpeed: 320,
      },
      {
        x: 350,
        y: 500,
        type: "straight",
        zone: "Main Straight",
        sector: 3,
        targetSpeed: 330,
      },
      {
        x: 150,
        y: 480,
        type: "corner",
        zone: "Turn 1",
        sector: 1,
        targetSpeed: 100,
      },
      {
        x: 100,
        y: 300,
        type: "corner",
        zone: "Turns 2-4",
        sector: 1,
        targetSpeed: 150,
      },
      {
        x: 200,
        y: 100,
        type: "straight",
        zone: "Straight",
        sector: 1,
        targetSpeed: 290,
      },
      {
        x: 400,
        y: 100,
        type: "corner",
        zone: "Turns 6-8",
        sector: 2,
        targetSpeed: 180,
      },
      {
        x: 500,
        y: 200,
        type: "straight",
        zone: "Straight",
        sector: 2,
        targetSpeed: 300,
      },
      {
        x: 550,
        y: 350,
        type: "corner",
        zone: "Turns 12-14",
        sector: 2,
        targetSpeed: 120,
      },
      {
        x: 400,
        y: 400,
        type: "straight",
        zone: "Straight",
        sector: 3,
        targetSpeed: 310,
      },
      {
        x: 200,
        y: 450,
        type: "corner",
        zone: "Turn 16",
        sector: 3,
        targetSpeed: 110,
      },
    ],
    yas_marina: [
      {
        x: 650,
        y: 500,
        type: "straight",
        zone: "Main Straight",
        sector: 3,
        targetSpeed: 300,
      },
      {
        x: 350,
        y: 500,
        type: "straight",
        zone: "Main Straight",
        sector: 3,
        targetSpeed: 315,
      },
      {
        x: 150,
        y: 480,
        type: "corner",
        zone: "Turns 1-4",
        sector: 1,
        targetSpeed: 150,
      },
      {
        x: 100,
        y: 300,
        type: "straight",
        zone: "Straight",
        sector: 1,
        targetSpeed: 280,
      },
      {
        x: 200,
        y: 100,
        type: "corner",
        zone: "Turns 5-6",
        sector: 1,
        targetSpeed: 180,
      },
      {
        x: 400,
        y: 100,
        type: "straight",
        zone: "Straight",
        sector: 2,
        targetSpeed: 290,
      },
      {
        x: 500,
        y: 200,
        type: "corner",
        zone: "Turns 9-11",
        sector: 2,
        targetSpeed: 120,
      },
      {
        x: 550,
        y: 350,
        type: "straight",
        zone: "Straight",
        sector: 2,
        targetSpeed: 270,
      },
      {
        x: 400,
        y: 400,
        type: "corner",
        zone: "Turns 13-15",
        sector: 3,
        targetSpeed: 100,
      },
      {
        x: 200,
        y: 450,
        type: "straight",
        zone: "Straight",
        sector: 3,
        targetSpeed: 260,
      },
    ],
  },

  get(circuitId) {
    return this.layouts[circuitId] || this.defaultKeyPoints;
  },
};
