<?php

use App\Models\Driver;
use Illuminate\Database\Seeder;

class DriverSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $drivers = [
            [
                'name' => 'Max Verstappen',
                'image' => 'https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyNC9kcml2ZXJzL2hlYWRzaG90cy9mMS92ZXIucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo3MH19fQ==',
                'cornering' => 96,
                'braking' => 96,
                'reactions' => 89,
                'control' => 90,
                'smoothness' => 89,
                'adaptability' => 89,
                'overtaking' => 92,
                'defending' => 98,
                'accuracy' => 86,
                'salary_per_race' => null,
                'created_by' => 1,
            ],
            [
                'name' => 'Fernando Alonso',
                'image' => 'https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyNC9kcml2ZXJzL2hlYWRzaG90cy9mMS9hbG8ucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo3MH19fQ==',
                'cornering' => 90,
                'braking' => 91,
                'reactions' => 86,
                'control' => 94,
                'smoothness' => 87,
                'adaptability' => 86,
                'overtaking' => 91,
                'defending' => 91,
                'accuracy' => 88,
                'salary_per_race' => null,
                'created_by' => 1,
            ],
            [
                'name' => 'Lewis Hamilton',
                'image' => 'https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyNC9kcml2ZXJzL2hlYWRzaG90cy9mMS9oYW0ucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo3MH19fQ==',
                'cornering' => 93,
                'braking' => 95,
                'reactions' => 86,
                'control' => 92,
                'smoothness' => 86,
                'adaptability' => 87,
                'overtaking' => 90,
                'defending' => 94,
                'accuracy' => 83,
                'salary_per_race' => null,
                'created_by' => 1,
            ],
            [
                'name' => 'Charles Leclerc',
                'image' => 'https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyNC9kcml2ZXJzL2hlYWRzaG90cy9mMS9sZWMucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo3MH19fQ==',
                'cornering' => 94,
                'braking' => 94,
                'reactions' => 86,
                'control' => 89,
                'smoothness' => 83,
                'adaptability' => 81,
                'overtaking' => 87,
                'defending' => 91,
                'accuracy' => 86,
                'salary_per_race' => null,
                'created_by' => 1,
            ],
            [
                'name' => 'Lando Norris',
                'image' => 'https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyNC9kcml2ZXJzL2hlYWRzaG90cy9mMS9ub3IucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo3MH19fQ==',
                'cornering' => 90,
                'braking' => 89,
                'reactions' => 85,
                'control' => 96,
                'smoothness' => 95,
                'adaptability' => 78,
                'overtaking' => 86,
                'defending' => 87,
                'accuracy' => 80,
                'salary_per_race' => null,
                'created_by' => 1,
            ],
            [
                'name' => 'Carlos Sainz',
                'image' => 'https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyNC9kcml2ZXJzL2hlYWRzaG90cy9mMS9zYWkucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo3MH19fQ==',
                'cornering' => 91,
                'braking' => 92,
                'reactions' => 87,
                'control' => 86,
                'smoothness' => 80,
                'adaptability' => 81,
                'overtaking' => 90,
                'defending' => 94,
                'accuracy' => 86,
                'salary_per_race' => null,
                'created_by' => 1,
            ],
            [
                'name' => 'George Russell',
                'image' => 'https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyNC9kcml2ZXJzL2hlYWRzaG90cy9mMS9ydXMucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo3MH19fQ==',
                'cornering' => 85,
                'braking' => 87,
                'reactions' => 87,
                'control' => 88,
                'smoothness' => 85,
                'adaptability' => 96,
                'overtaking' => 81,
                'defending' => 86,
                'accuracy' => 92,
                'salary_per_race' => null,
                'created_by' => 1,
            ],
            [
                'name' => 'Sergio Pérez',
                'image' => 'https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyNC9kcml2ZXJzL2hlYWRzaG90cy9mMS9wZXIucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo3MH19fQ==',
                'cornering' => 86,
                'braking' => 86,
                'reactions' => 91,
                'control' => 90,
                'smoothness' => 82,
                'adaptability' => 74,
                'overtaking' => 91,
                'defending' => 91,
                'accuracy' => 85,
                'salary_per_race' => null,
                'created_by' => 1,
            ],
            [
                'name' => 'Valtteri Bottas',
                'image' => 'https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyNC9kcml2ZXJzL2hlYWRzaG90cy9mMS9ib3QucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo3MH19fQ==',
                'cornering' => 86,
                'braking' => 86,
                'reactions' => 82,
                'control' => 90,
                'smoothness' => 75,
                'adaptability' => 72,
                'overtaking' => 81,
                'defending' => 87,
                'accuracy' => 93,
                'salary_per_race' => null,
                'created_by' => 1,
            ],
            [
                'name' => 'Pierre Gasly',
                'image' => 'https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyNC9kcml2ZXJzL2hlYWRzaG90cy9mMS9nYXMucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo3MH19fQ==',
                'cornering' => 84,
                'braking' => 83,
                'reactions' => 80,
                'control' => 91,
                'smoothness' => 88,
                'adaptability' => 93,
                'overtaking' => 83,
                'defending' => 82,
                'accuracy' => 77,
                'salary_per_race' => null,
                'created_by' => 1,
            ],
            [
                'name' => 'Esteban Ocon',
                'image' => 'https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyNC9kcml2ZXJzL2hlYWRzaG90cy9mMS9vY28ucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo3MH19fQ==',
                'cornering' => 81,
                'braking' => 81,
                'reactions' => 82,
                'control' => 84,
                'smoothness' => 83,
                'adaptability' => 81,
                'overtaking' => 83,
                'defending' => 84,
                'accuracy' => 93,
                'salary_per_race' => null,
                'created_by' => 1,
            ],
            [
                'name' => 'Oscar Piastri',
                'image' => 'https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyNC9kcml2ZXJzL2hlYWRzaG90cy9mMS9waWEucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo3MH19fQ==',
                'cornering' => 83,
                'braking' => 82,
                'reactions' => 84,
                'control' => 90,
                'smoothness' => 77,
                'adaptability' => 88,
                'overtaking' => 80,
                'defending' => 83,
                'accuracy' => 84,
                'salary_per_race' => null,
                'created_by' => 1,
            ],
            [
                'name' => 'Alexander Albon',
                'image' => 'https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyNC9kcml2ZXJzL2hlYWRzaG90cy9mMS9hbGIucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo3MH19fQ==',
                'cornering' => 81,
                'braking' => 82,
                'reactions' => 87,
                'control' => 85,
                'smoothness' => 80,
                'adaptability' => 85,
                'overtaking' => 84,
                'defending' => 86,
                'accuracy' => 79,
                'salary_per_race' => null,
                'created_by' => 1,
            ],
            [
                'name' => 'Nico Hülkenberg',
                'image' => 'https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyNC9kcml2ZXJzL2hlYWRzaG90cy9mMS9odWwucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo3MH19fQ==',
                'cornering' => 82,
                'braking' => 81,
                'reactions' => 88,
                'control' => 85,
                'smoothness' => 81,
                'adaptability' => 86,
                'overtaking' => 79,
                'defending' => 79,
                'accuracy' => 82,
                'salary_per_race' => null,
                'created_by' => 1,
            ],
            [
                'name' => 'Yuki Tsunoda',
                'image' => 'https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyNC9kcml2ZXJzL2hlYWRzaG90cy9mMS90c3UucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo3MH19fQ==',
                'cornering' => 83,
                'braking' => 83,
                'reactions' => 85,
                'control' => 77,
                'smoothness' => 82,
                'adaptability' => 78,
                'overtaking' => 85,
                'defending' => 83,
                'accuracy' => 89,
                'salary_per_race' => null,
                'created_by' => 1,
            ],
            [
                'name' => 'Daniel Ricciardo',
                'image' => 'https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyNC9kcml2ZXJzL2hlYWRzaG90cy9mMS9yaWMucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo3MH19fQ==',
                'cornering' => 79,
                'braking' => 79,
                'reactions' => 81,
                'control' => 86,
                'smoothness' => 86,
                'adaptability' => 78,
                'overtaking' => 81,
                'defending' => 82,
                'accuracy' => 85,
                'salary_per_race' => null,
                'created_by' => 1,
            ],
            [
                'name' => 'Lance Stroll',
                'image' => 'https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyNC9kcml2ZXJzL2hlYWRzaG90cy9mMS9zdHIucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo3MH19fQ==',
                'cornering' => 80,
                'braking' => 79,
                'reactions' => 79,
                'control' => 84,
                'smoothness' => 80,
                'adaptability' => 92,
                'overtaking' => 83,
                'defending' => 84,
                'accuracy' => 85,
                'salary_per_race' => null,
                'created_by' => 1,
            ],
            [
                'name' => 'Kevin Magnussen',
                'image' => 'https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyNC9kcml2ZXJzL2hlYWRzaG90cy9mMS9tYWcucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo3MH19fQ==',
                'cornering' => 81,
                'braking' => 78,
                'reactions' => 83,
                'control' => 83,
                'smoothness' => 78,
                'adaptability' => 91,
                'overtaking' => 79,
                'defending' => 76,
                'accuracy' => 79,
                'salary_per_race' => null,
                'created_by' => 1,
            ],
            [
                'name' => 'Guanyu Zhou',
                'image' => 'https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyNC9kcml2ZXJzL2hlYWRzaG90cy9mMS96aG8ucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo3MH19fQ==',
                'cornering' => 78,
                'braking' => 79,
                'reactions' => 80,
                'control' => 84,
                'smoothness' => 79,
                'adaptability' => 78,
                'overtaking' => 81,
                'defending' => 75,
                'accuracy' => 80,
                'salary_per_race' => null,
                'created_by' => 1,
            ],
            [
                'name' => 'Logan Sargeant',
                'image' => 'https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyNC9kcml2ZXJzL2hlYWRzaG90cy9mMS9zYXIucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo3MH19fQ==',
                'cornering' => 77,
                'braking' => 79,
                'reactions' => 81,
                'control' => 79,
                'smoothness' => 74,
                'adaptability' => 80,
                'overtaking' => 71,
                'defending' => 76,
                'accuracy' => 81,
                'salary_per_race' => null,
                'created_by' => 1,
            ],
        ];

        Driver::insert($drivers);
    }
}
